server:
  port: 8080

spring:
  application:
    name: zxf-springboot-trace-webmvc
  profiles:
    include: trace-my

logging:
  level:
    root: INFO
    zxf.trace: DEBUG
    org.springframework.web: INFO
