trace:
  mdc-injection:
    enable: true
    key: ReqId
    header: X-Request-Id
  sensitive-mask:
    headers:
      - Token
      - Authorization
      - Cookie
      - Set-Cookie
    json-names:
      - email
      - token
      - id